version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "7364:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./shared_folder/mysql:/var/lib/mysql
      - ./docker_mysql:/docker-entrypoint-initdb.d
  web:
    image: teamtat
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db